id: AD580BFC7
title: Toh_736-The_Dharani_of_Parnasavari-v2
type: translation
pechas:
- IF777BAA5
- I4716ACDD
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-013
  eft-text-version: 1.1.2 2020
  title: Toh_736-The_Dharani_of_Parnasavari-v2
alignment_to_base:
  IF777BAA5/BE9C: E215
  I4716ACDD/0078: E215
